src/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <externalId>true</externalId>
        <label>Unique Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page_Layout__c.object
<CustomObject>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <externalId>true</externalId>
        <label>Unique Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Page Layout</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Page Layouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page_Layout_Field__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <referenceTo>Field__c</referenceTo>
        <relationshipLabel>Page Layout Fields</relationshipLabel>
        <relationshipName>Page_Layout_Fields</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Page_Layout__c</fullName>
        <label>Page Layout</label>
        <referenceTo>Page_Layout__c</referenceTo>
        <relationshipLabel>Page Layout Fields</relationshipLabel>
        <relationshipName>Page_Layout_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <externalId>true</externalId>
        <label>Unique Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Page Layout Field</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Page Layout Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PageLayoutFieldClass.cls
public with sharing class PageLayoutFieldClass{

    public static List<Page_Layout_Field__c> build(PageLayoutClass layout){
        List<Page_Layout_Field__c> pageLayoutFields = new List<Page_Layout_Field__c>();
        for (String field : layout.getFields()){
            if (isCustomField(field)){
                pageLayoutFields.add(
                    new Page_Layout_Field__c(
                         Name = layout.getName() + '-' + field
                        ,Unique_Name__c = layout.getName() + '-' + field 
                        ,Page_Layout__r = new Page_Layout__c(Unique_Name__c = layout.getName())
                        ,Field__r = new Field__c(Unique_Name__c = layout.getObjectName() + '.' + field)
                    )
                );
            }
        }

        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.allowFieldTruncation = true;

        for (Page_Layout_Field__c plf : pageLayoutFields){
            plf.setOptions(dmo);
        }
        return pageLayoutFields;
    }

    private static boolean isCustomField(string fieldName){
        if (fieldName == null) return false;
        if (fieldName == 'null') return false;
        return fieldName.endsWith('__c');
    }
}