src/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <externalId>true</externalId>
        <label>Unique Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/List_View__c.object
<CustomObject>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <externalId>true</externalId>
        <label>Unique Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>List View</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Views</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/List_View_Field__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <referenceTo>Field__c</referenceTo>
        <relationshipLabel>List View Fields</relationshipLabel>
        <relationshipName>List_View_Fields</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>List_View__c</fullName>
        <label>List View</label>
        <referenceTo>List_View__c</referenceTo>
        <relationshipLabel>List View Fields</relationshipLabel>
        <relationshipName>List_View_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <picklist>
            <picklistValues>
                <fullName>EQUALS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT EQUALS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <externalId>true</externalId>
        <label>Unique Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>List View Field</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List View Fields</pluralLabel>
    <recordTypes>
        <fullName>Column</fullName>
        <active>true</active>
        <label>Column</label>
    </recordTypes>
    <recordTypes>
        <fullName>Filter</fullName>
        <active>true</active>
        <label>Filter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ListViewFieldClass.cls
public with sharing class ListViewFieldClass{

    public List_View_Field__c listViewFieldObj;
    public string fieldName;

    public ListViewFieldClass(ListViewClass listView, String columnName){
        this.fieldName = listView.getObjectName() + '.' + columnName;
        this.listViewFieldObj = new List_View_Field__c(
                Name = fieldName
                ,Field__r = new Field__c(Unique_Name__c = this.fieldName)
                ,List_View__r = new List_View__c(Unique_Name__c = listView.getUniqueName())
                ,Unique_Name__c = listView.getUniqueName() + '.' + fieldName + '.column'
        );
    }
    public ListViewFieldClass(ListViewClass listView, MetadataService.ListViewFilter filter){
        this.fieldName = listView.getObjectName() + '.' + filter.field;
        this.listViewFieldObj = new List_View_Field__c(
                Name = fieldName
                ,Field__r = new Field__c(Unique_Name__c = this.fieldName)
                ,List_View__r = new List_View__c(Unique_Name__c = listView.getUniqueName())
                ,Operation__c = filter.operation
                ,Value__c = filter.value
                ,Unique_Name__c = listView.getUniqueName() + '.' + fieldName + '.filter'
        );
    }

    public static List<List_View_Field__c> build(ListViewClass listView){
        List<List_View_Field__c> listViewFields = new List<List_View_Field__c>();
        listViewFields.addAll(parseColumns(listView));
        listViewFields.addAll(parseFilters(listView));

        return listViewFields;
    }

    private static boolean isCustomField(String fieldName){
        if (fieldName == null) return false;
        return fieldName.endsWith('__c');

    }
    private static boolean isCustomField(MetadataService.ListViewFilter filter){
        return isCustomField(filter.field);
    }

    private static List<List_View_Field__c> parseFilters(ListViewClass listView){
        List<List_View_Field__c> filters = new List<List_View_Field__c>();
        try {
            for (MetadataService.ListViewFilter filter : listView.listViewMetadata.filters){
                //only supporting custom fields right now, due to how standard fields are represented differently in different places.
                if (isCustomField(filter)) filters.add(new ListViewFieldClass(listView, filter).listViewFieldObj);
            }
        } catch (Exception e){
            system.debug(e);
            system.debug(JSON.serializePretty(listView));
        }
        return filters;
    }

    private static List<List_View_Field__c> parseColumns(ListViewClass listView){
        List<List_View_Field__c> columns  = new List<List_View_Field__c>();
        try {
            for (String column : listView.listViewMetadata.columns){
                //only supporting custom fields right now, due to how standard fields are represented differently in different places.
                if (isCustomField(column)) columns.add(new ListViewFieldClass(listView, column).listViewFieldObj);
            }
        } catch (Exception e){
            system.debug(e);
            system.debug(JSON.serializePretty(listView));
        }
        return columns;
    }
}