src/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>anytype</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>base64</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Combobox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DataCategoryGroupReference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DateTime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EncryptedString</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MultiPicklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TextArea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>URL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <externalId>true</externalId>
        <label>Unique Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>isCalculated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isCalculated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sObject__c</fullName>
        <label>sObject</label>
        <referenceTo>sObject__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/sObject__c.object
<CustomObject>
    <fields>
        <fullName>API_Name__c</fullName>
        <externalId>true</externalId>
        <label>API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>sObject</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieldClass.cls
public class FieldClass {
    /** 
    https://www.salesforce.com/us/developer/docs/apexcode/Content/apex_methods_system_fields_describe.htm
    **/

    public Field__c fieldObj;
    
    public FieldClass(Schema.SObjectField sObjField, string objName){
        Schema.DescribeFieldResult describe = sObjField.getDescribe();
        this.fieldObj = new Field__c();
        this.fieldObj.Name = describe.getLabel();
        this.fieldObj.Unique_Name__c = objName + '.' + describe.getName();
        this.fieldObj.sObject__r = new sObject__c(API_Name__c = objName);
        this.fieldObj.Type__c = describe.getType().name();
        this.fieldObj.isCalculated__c = describe.isCalculated();
    }
    
    public static void findAndInsertSObjectFields(string sObjectName){
        List<Field__c> sObjectFields = new List<Field__c>();
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Schema.DescribeSObjectResult r = gd.get(sObjectName).getDescribe();
        Map<String, Schema.SObjectField> fs = r.fields.getMap();
        for (String fieldName : fs.keySet()) {
            sObjectFields.add(new FieldClass(fs.get(fieldName), sObjectName).fieldObj);
        }
         
        upsert sObjectFields Unique_Name__c;
    }

}