src/objects/sObject__c.object
<CustomObject>
    <fields>
        <fullName>API_Name__c</fullName>
        <externalId>true</externalId>
        <label>API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>sObject</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieldClassBatch.cls
global class FieldClassBatch implements Database.Batchable<sObject>, Database.Stateful {

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, Name, API_Name__c FROM sObject__c]);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject__c> sObjects){
        for (sObject__c sObj : sObjects){
            FieldClass.findAndInsertSObjectFields(sObj.API_Name__c);
        }
    }
    
    global void finish(Database.BatchableContext BC){}
}