src/objects/sObject__c.object
<CustomObject>
    <fields>
        <fullName>API_Name__c</fullName>
        <externalId>true</externalId>
        <label>API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>sObject</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sObjectClass.cls
public class sObjectClass {

    /**
        https://www.salesforce.com/us/developer/docs/apexcode/Content/apex_methods_system_sobject_describe.htm
    **/

    public sObject__c sObj;
    
    public sObjectClass(Schema.DescribeSObjectResult describeResult){
        this.sObj = new sObject__c();
        this.sObj.Name = describeResult.getLabel();
        this.sObj.API_Name__c = describeResult.getName();
    }
    
    public static void findAndInsertSObjects(){
        List<sObject__c> sObjects = new List<sObject__c>();
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        for (String sObjectName : gd.keySet()){
            Schema.DescribeSObjectResult r = gd.get(sObjectName).getDescribe();
            sObjects.add(new sObjectClass(r).sObj);
        }
        upsert sObjects API_Name__c;
    }

}